import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import Image from "next/image";
import logo from "@/assets/logo.png";
import { IoLocationSharp, IoLogoApple } from "react-icons/io5";
import { MdEmail } from "react-icons/md";
import { FaApple } from "react-icons/fa";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-between  items-center mx-16 my-6">
          <Image src={logo} width={60} height={60} className="rounded-xl" />
          <div className="flex justify-between gap-5">
            <p>Emotions</p>
            <p>Manifesto</p>
            <p>Self-awareness test</p>
            <p>Work with us</p>
          </div>
          <button className="bg-black text-white p-3 rounded-full">
            Download app
          </button>
        </header>
        {children}
        <footer className="h-20">
          <hr></hr>
          <div className="flex flex-col items-center justify-center gap-2 mt-2">
            <Image src={logo} width={60} height={60} className="rounded-xl" />
            <p className="text-xl text-violet-400 font-bold">ahead</p>
            <div className="flex gap-5">
              <div className="flex items-center gap-2">
                <div className="flex justify-center items-center bg-violet-400 p-1 rounded-full">
                  <IoLocationSharp size={24} />
                </div>
                Bangalore,India
              </div>
              <div className="flex items-center gap-2">
                <div className="flex justify-center items-center bg-violet-400 p-1 rounded-full">
                  <MdEmail size={24} />
                </div>
                ahead@gmail.com
              </div>
            </div>
            <div className="flex bg-black text-white rounded-xl py-2 px-4">
              <IoLogoApple size={40} />
              <div className="flex flex-col justify-center">
                <p className="text-xs">Download on the</p>
                <p className="text-xl font-bold">App Store</p>
              </div>
            </div>
            <p>@ 2022 Ahead app.all rights reserved</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
